global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:3000"]

  - job_name: "authentication"
    static_configs:
      - targets: ["authentication:3001"]

  - job_name: "orders"
    static_configs:
      - targets: ["orders:3002"]

  - job_name: "payments"
    static_configs:
      - targets: ["payments:3003"]
